"""Register #167 (tradability filter) and the episode-placebo amendment
in docs/cleanroom.md. Runs BEFORE H-basket-B/C. Research rule 3."""
import os
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
df = pd.read_csv(os.path.join(ROOT, "research", "basket_tradability.csv"))
tr = df[df.tradable].sort_values("flat")
fa = df[~df.tradable].sort_values("flat")

L = []
A = L.append
A("\n## Hypothesis #167 — TRADABILITY FILTER (registered before B/C ran)\n")
A("**#163-#166 STAND AS REGISTERED.** They were registered on the full")
A("86-ticker universe and that is the universe they describe. Nothing about")
A("them is being rewritten, narrowed, or re-run under a new definition.")
A("**#167 is a TRADABLE-SUBSET VARIANT** carried alongside them, not a")
A("replacement for them. H-basket-B is reported on BOTH the #167 subset and")
A("the full 82 so the filter's effect is visible rather than hidden.\n")
A("### The filter, defined on PRICES ONLY and decided now\n")
A("A ticker is **tradable** if, over SEALED:\n")
A("1. its share of flat 4h bars (`High == Low`) is **<= 10%**, AND")
A("2. its median `1.5 x ATR` stop is **>= 0.5% of entry**.\n")
A("Both are properties of the price series alone. Neither looks at a")
A("direction label, a trade outcome, an expectancy, or any result from")
A("#163-#166. The motivation is recorded above: on pairs that barely trade")
A("on Binance.US the 4h bars are flat, the ATR collapses, and the derived")
A("stop lands 0.025% from entry — at which point 8bps of round-trip cost is")
A("3.2R of risk and the trade is uneconomic before it starts. The filter")
A("removes instruments whose ATR is not a usable risk unit. It is NOT a")
A("performance screen.\n")
A("### Result: 26 of 82 tradable\n")
A("All 56 exclusions fail on the flat-bar criterion; **0 tickers fail the")
A("stop criterion independently** (the two are near-collinear, as expected —")
A("flat bars are what collapse the ATR).\n")
A("**TRADABLE (26):**\n")
A("| ticker | flat 4h bars | median 1.5xATR stop |")
A("|--------|--------------|---------------------|")
for _, r in tr.iterrows():
    A("| %s | %.2f%% | %.3f%% |" % (r.ticker, 100 * r.flat, r.med_stop_pct))
A("")
A("**EXCLUDED (56):** " + " ".join(fa.ticker) + "\n")

A("### Amendment registered now: EPISODE-MATCHED PLACEBO\n")
A("H-basket-B's placebo draws random **EPISODES matching the incumbent's")
A("observed run-length distribution per ticker**, not independent days.\n")
A("Why, recorded before the numbers: the incumbent's 19 BTC STRONG_BUY")
A("trades come from only **8 episodes** — consecutive signal days riding one")
A("price move, several of which exit on the same 4h bar. An independent-day")
A("placebo scatters its draws and gets near-independent outcomes, so it is")
A("**lower-variance than the thing it benchmarks**, and the incumbent clears")
A("its p95 far more easily than the percentile implies. That flaw was")
A("already recorded against the Prompt-1 reference rows; this fixes it.\n")
A("Construction, per ticker: take the observed run-lengths of consecutive")
A("STRONG_BUY signal days; draw the same NUMBER of runs with the same")
A("LENGTHS at random non-overlapping start positions in the same window;")
A("apply the same 2-day confirm, so a run of length L yields L-1 trades")
A("exactly as the observed runs do. **300 seeds.**\n")
A("Everything else in H-basket-B and H-basket-C is unchanged from #164/#165:")
A("the same pooled statistics, the same time-cut folds, and the same")
A("registered pass directions — `ex_best` > 0 on BOTH windows AND `net_all`")
A("above the placebo p95 on BOTH for B; positive in ALL FOUR quartiles for C.")
A("H-tier-curve (#166) stays DESCRIPTIVE and selects nothing.\n")

path = os.path.join(ROOT, "docs", "cleanroom.md")
src = open(path, encoding="utf-8").read()
open(path, "w", encoding="utf-8").write(src.rstrip("\n") + "\n" + "\n".join(L))
print("registered #167: %d tradable of %d" % (len(tr), len(df)))
