"""Record the H-basket-A (#163) result in docs/cleanroom.md."""
import os
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
df = pd.read_csv(os.path.join(ROOT, "research", "basket_A_strong_buy.csv"))
df = df.sort_values("n", ascending=False)

L = []
A = L.append
A("\n## Result of H-basket-A (#163) — recorded 2026-08-27\n")
A("Incumbent UNCHANGED (`LIVE_GEOMETRY`, same thresholds, 2+2bps per side),")
A("STRONG_BUY tier, SEALED window **2019-09-24 -> 2026-02-26**. Windows common")
A("to all tickers, anchored on BTC. Lockbox 2026-02-26 -> 2026-08-26 never read;")
A("4h feed sealed at the boundary.\n")

A("### Export outcome: 82 of 86 tickers frozen\n")
A("| symbol | outcome | detail |")
A("|--------|---------|--------|")
A("| COMPUSDT | **excluded** | run_backtest raised: no overlapping dates between squeeze and technical history |")
A("| SHIBUSDT | **excluded** | run_backtest raised: no overlapping dates |")
A("| IMXUSDT | **excluded** | thin-merged guard: 59 rows after the inner join |")
A("| GRTUSDT | **excluded** | thin-merged guard: 44 rows after the inner join |")
A("")
A("The overlap assertion (guard 3) flagged three more that were KEPT, since")
A("excluding a ticker after seeing its data would be rule-4 curation:\n")
A("- `ONEUSDT` — merged 712 rows vs a raw date intersection of 2,192 (**32.5%**).")
A("  A 1,480-day silent truncation by the `how=\"inner\"` join at pipeline.py:931.")
A("- `UNIUSDT` — 1,636 of 2,006 (81.6%); `APEUSDT` — 1,291 of 1,624 (79.5%).")
A("  Both roughly consistent with indicator warm-up plus gaps.")
A("")
A("The overlap fraction compares the merged frame to the RAW date intersection,")
A("which ignores ~200 rows of indicator warm-up and any dropna, so it is an")
A("upper bound. ONE at 32.5% is far beyond that; UNI/APE around 80% are not.\n")

A("### HEADLINE: 0 of 82 tickers reach a defined `ex_best`\n")
A("`ex_best` needs >=3 folds carrying >=10 trades each, i.e. >=30 trades placed")
A("in the right shape across 6.4 years. **No ticker in the basket reaches it.**")
A("The densest, BICO, fires 32 STRONG_BUY trades — which spread over 4 folds is")
A("8 per fold, under the bar. Raising event rate from 3 tickers to 82 moved the")
A("count from 0 of 3 to **0 of 82**.\n")
A("- tickers with 0 STRONG_BUY trades: **3** (ENJ, ONE, THETA)")
A("- median trades per ticker: **6**")
A("- total STRONG_BUY trades across the basket: **645**")
A("- total independent episodes (>15d apart): **306**")
A("- best single ticker: BICO, 32 trades / 8 episodes — still 0 counted folds\n")
A("The tier is not rare because BTC is unusual. It is rare **per ticker,")
A("everywhere**, and widening the universe does not fix that: it produces many")
A("thin per-ticker records rather than one thick one. Pooling (H-basket-B) is")
A("the only route to a defined `ex_best`, and pooling is exactly what breaks")
A("the per-ticker independence `ex_best` assumes.\n")

A("### DEFECT FOUND — 2-decimal rounding corrupts sub-dollar tickers\n")
A("**This program surfaced a latent defect in the incumbent.**")
A("`signal_engines.compute_exit_levels` returns `entry`, `target` and `stop`")
A("**rounded to 2 decimals** (signal_engines.py:495-497). At BTC's $78,000 that")
A("is immaterial. For a token trading at $0.00145, entry, target and stop all")
A("round to `0.00`, and then:\n")
A("- `stop_dist = abs(entry - stop) = 0`, so `resolve_on_4h` returns")
A("  `pnl_r = nan` (pipeline.py:1586, the `if stop_dist else nan` branch);")
A("- `hi >= target` is trivially true against a target of `0.00`, so the trade")
A("  is labelled **`target`** on its first bar — a manufactured 100% win rate;")
A("- `stats_from_trades` averages with `.mean()`, which SKIPS NaN. So `win%`")
A("  is computed over ALL trades while `net_all` is computed over only the")
A("  non-NaN ones. **The two columns describe different trade sets.**\n")
A("That is why the raw table contains impossible rows: SYS at 75% win and")
A("-1.003R, RAD at 84.2% and -1.000R, and SLP/VTHO/NMR at 100% win with a NaN")
A("expectancy.\n")
A("Measured contamination on SEALED:\n")
A("- **185 of 645 STRONG_BUY trades (28.7%) carry `pnl_r = NaN`**")
A("- **35 of 82 tickers** have at least one such trade")
A("- 29 of the 45 tickers under $1 median close are affected — and so are 6")
A("  tickers ABOVE $1 (e.g. RAD, median $1.25, 84% of its trades NaN). The")
A("  trigger is not price alone: it is `1.5 x ATR` falling under half a cent in")
A("  absolute terms, so low volatility reaches it at higher prices too.\n")
A("**The headline survives this.** On the 44 clean tickers (no NaN trades,")
A("224 trades), the answer is still **0 of 44** with a defined `ex_best`. Trade")
A("COUNTS are unaffected by the rounding; only the P&L columns are.\n")
A("**Consequence for H-basket-B and H-basket-C: they must not run yet.** Both")
A("pool `net_all` and `ex_best` across tickers, and 28.7% of the pooled trades")
A("would contribute a NaN that `.mean()` silently drops — pooling a biased")
A("subset while reporting a win rate over the full set. The fix belongs in")
A("`signal_engines.compute_exit_levels`, a core file, so under research rule 1")
A("it is a separate decision and a separate commit, not something research")
A("changes on its own. It also alters live behaviour for any sub-dollar asset.\n")

A("### Per-ticker table (SEALED, STRONG_BUY)\n")
A("`net_all` / `win%` marked * are contaminated by the rounding defect and")
A("must not be read as results. `ex_best` is `—` for every ticker: none")
A("reached 3 counted folds.\n")
A("| ticker | events | trades | episodes | win% | net_all | ex_best | folds+/counted |")
A("|--------|--------|--------|----------|------|---------|---------|----------------|")
for _, r in df.iterrows():
    eb = "—"
    win = "—" if not r.n else ("%.1f" % r.win_pct)
    net = "—" if not r.n else ("%+.3f" % r.net_all if r.net_all == r.net_all else "NaN")
    A("| %s | %d | %d | %d | %s | %s | %s | %d/%d |"
      % (r.ticker, r.event_days, r.n, r.episodes, win, net, eb,
         r.folds_pos, r.folds_counted))
A("")
A("Full machine-readable table: `research/basket_A_strong_buy.csv`.")
A("Basket frames: `data/basket/` (19MB, gitignored; MANIFEST records every")
A("ticker's status, spans and overlap fraction).\n")

path = os.path.join(ROOT, "docs", "cleanroom.md")
src = open(path, encoding="utf-8").read()
open(path, "w", encoding="utf-8").write(src.rstrip("\n") + "\n" + "\n".join(L))
print("recorded H-basket-A result (%d ticker rows)" % len(df))
