"""Record the rounding fix, the re-run of H-basket-A, and the liquidity
finding in docs/cleanroom.md."""
import os
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
a = pd.read_csv(os.path.join(ROOT, "research", "basket_A_before_fix.csv")).set_index("ticker")
b = pd.read_csv(os.path.join(ROOT, "research", "basket_A_strong_buy.csv")).set_index("ticker")

L = []
A = L.append
A("\n## Exit-level rounding defect — FIXED, and H-basket-A re-run\n")
A("Commit `ffa3191`, tests first. Recorded here because the H-basket-A")
A("numbers above were produced with the defect present.\n")
A("### What was wrong\n")
A("`compute_exit_levels` rounded entry/target/stop to a FIXED 2 decimals.")
A("For an asset at $0.00145 all three collapse onto `0.00`, so `stop_dist`")
A("was 0, `resolve_on_4h` returned NaN `pnl_r`, `high >= target` was")
A("trivially true against a target of 0.00 (a manufactured 100% win rate),")
A("and `stats_from_trades` averaged with `.mean()`, which SKIPS NaN --")
A("reporting a win rate over every trade and an expectancy over only the")
A("survivors. **The live bot has been publishing with this**; BTC/ETH/SOL")
A("were never affected, which is why 5.5 years of reporting never caught it.\n")
A("### The fix\n")
A("- `_price_round`: 8 SIGNIFICANT FIGURES relative to the entry price, so")
A("  the geometry is identical at $78,000 and $0.00145. All three levels")
A("  round against the same reference, preserving their spacing.")
A("- `compute_exit_levels` never returns a zero stop distance (falls back to")
A("  unrounded, else `applicable=False`), and now returns `stop_dist`.")
A("- `resolve_on_4h` RAISES on zero stop distance instead of returning NaN.")
A("- `stats_from_trades` RAISES on any NaN P&L instead of averaging around it.")
A("- 8 new tests (`TestExitLevelPrecision`), 6 of which failed on the old")
A("  code. Suite: **381 passed, 2 skipped**.\n")
A("### Verification after the fix\n")
A("| check | result |")
A("|-------|--------|")
A("| trades with NaN `pnl_r` | **0** (was 185 of 645, 28.7%) |")
A("| 100%-win rows with NaN expectancy | **0** (was 3: SLP, VTHO, NMR) |")
A("| rows above the 2.667R theoretical max | **0** (ZRX previously showed +3.314R) |")
A("| tickers whose `net_all` changed | 74 of 82 |")
A("| tickers unchanged | 8, including BTC and ETH bit-identical |")
A("")
A("| ticker | n | win% before | win% after | net_all before | net_all after |")
A("|--------|---|-------------|------------|----------------|---------------|")
for t in ["BTC", "ETH", "BICO", "SYS", "RAD", "SLP", "VTHO"]:
    x, y = a.loc[t], b.loc[t]
    f = lambda v: "NaN" if v != v else "%+.3f" % v
    A("| %s | %d | %.1f | %.1f | %s | %s |"
      % (t, x.n, x.win_pct, y.win_pct, f(x.net_all), f(y.net_all)))
A("")
A("**The H-basket-A headline is unchanged: 0 of 82 tickers reach a defined")
A("`ex_best`**, on 645 trades and 306 episodes — identical counts, because")
A("the defect corrupted P&L columns, never trade selection.\n")

A("### NEW FINDING — the fix exposed degenerate ATR geometry on illiquid pairs\n")
A("Removing the NaN mask revealed something underneath. BICO went -1.004 ->")
A("-3.250R, SYS -1.003 -> -5.671R, RAD -1.000 -> **-9.323R**. A stop is -1R,")
A("so a mean of -9.3R looks impossible. It is not, and the arithmetic is now")
A("correct: `pnl_r` is properly bounded (-1.0 to +2.7). The magnitude comes")
A("entirely from `cost_r = 8bps / stop_fraction`. When the stop sits 0.025%")
A("from entry, 8bps of round-trip cost IS 3.2R of risk.\n")
A("Why the stops are that tight: **these pairs barely trade on Binance.US, so")
A("their 4h bars are flat and the ATR collapses.**\n")
A("| | flat 4h bars (High==Low) | median stop | median `cost_r` |")
A("|---|---|---|---|")
A("| BTC | 0.0% | 1.776% | 0.045R |")
A("| ETH | 0.0% | 2.003% | 0.040R |")
A("| SOL | 0.4% | 2.116% | 0.038R |")
A("| RAD | **73.3%** | **0.025%** | **3.24R** |")
A("| BICO | 70.9% | 0.050% | 1.61R |")
A("| LSK | **77.2%** | 0.070% | 1.14R |")
A("")
A("Across the 79 tickers that placed a trade: median flat-bar share **28.5%**")
A("(worst 79.1%); **46 tickers above 20%**, **20 above 50%**; **18 tickers**")
A("have a median `cost_r` above 0.1R and **9 above 1.0R**, against ~0.04R for")
A("the majors. Per-ticker figures in `research/basket_liquidity_health.csv`.\n")
A("**This is a real economic result, not an artifact:** on an asset whose ATR")
A("is a rounding error, an ATR-derived stop is not a risk unit, and the trade")
A("is uneconomic before it starts. But it means a pooled `net_all` over the")
A("basket would be dominated by cost artifacts from pairs that cannot")
A("actually be traded at this geometry.\n")
A("**Open decision before H-basket-B/C.** A liquidity precondition (e.g. a")
A("maximum flat-bar share, or a minimum stop fraction) would be the honest")
A("way to keep the pool tradeable — but the universe was registered at 86")
A("BEFORE any of this was seen, so narrowing it now is a NEW hypothesis")
A("needing its own number and its own pre-registration (research rule 4). It")
A("must not be applied retroactively to #163-#166 as though it had always")
A("been there. Recorded, not decided.\n")

path = os.path.join(ROOT, "docs", "cleanroom.md")
src = open(path, encoding="utf-8").read()
open(path, "w", encoding="utf-8").write(src.rstrip("\n") + "\n" + "\n".join(L))
print("recorded the fix + liquidity finding")
